language: node_js
node_js:
- '6'
script: npm test
deploy:
  provider: npm
  email: bleshik@gmail.com
  api_key:
    secure: aVyASEo7ZmQjXzqmIBb8UtgIFPQRL1aFniD+jK6uDXv8t6IzeCeKVneKWxkveraSjIX7ksLiq0oCKviYThoHApIjibAc92hsU5R5ulf87Zn6oPHjHX9vFuxvG6eMeBT8TFDlqzjfAYgcvn9vlKDXcAprM6VwnN5Dy7m+0nKvOEeSBbEV6cWFlTfkCLhaCNaTGcsEyJtJ4r5aY3oXt+7wy92bjLn2UGqSbBVYmRWQHrw6WX6CWwcxKexO28l8M8iCI0HBwbnPLK+D8v/J06C7jhG4A7ZKgLmijJZo+s5dRbAAWmdBJISvlRoVaVspAzFRaROcSBXlxqWMLS+CJEzzLT97rKqlQF/oveT1dQF64/XY5/zXwGrMPbXn9u1Scrx3TcnqEAdu5ioZ+umebGNoPivEbcKaYh8dn2tJBae6HuefIBMRDoUQx84WcciBy8gldrqKuIz4TCvnl+H8YpvmTUXmfYUpkLlGMLhys50orR14artkIkerrXXpvOxF6GkHAxcFykXFtygTCYCRqZwt31JRnf/n+804LZvwmUEu8OL/rA8GwlWmYJ8v6Jgobb8PUAdDiZZRmI2jaeVdKow6qg/7/UJIOoUjMyPurNI4uRFX00sIUKl6nv8Z/m8mAbqEihaC3xvlDtCUAGU/zJ0j0IwnLZJvi0RN0lksPYIX82Y=
